// Generated by CoffeeScript 1.7.1

/* */


/* */

(function() {
  var Sketch, checkLayer, content, contentStr, iconLayer, screenLayer, sendLayer, subject, subjectStr, _ref, _ref1, _ref2, _ref3;

  Sketch = Framer.Importer.load("imported/material");

  screenLayer = Sketch.screen;

  iconLayer = Sketch.icon;

  checkLayer = Sketch.check;

  sendLayer = Sketch.send;

  screenLayer.center();

  iconLayer.superLayer = screenLayer;

  _ref = [62, 62], iconLayer.width = _ref[0], iconLayer.height = _ref[1];

  checkLayer.superLayer = iconLayer;

  sendLayer.superLayer = iconLayer;

  _ref1 = [281, 145], iconLayer.x = _ref1[0], iconLayer.y = _ref1[1];

  iconLayer.style = {
    borderRadius: '32px',
    overflowY: 'hidden',
    webkitMaskImage: '-webkit-radial-gradient(circle, white, black)'
  };

  _ref2 = [0, 0], checkLayer.x = _ref2[0], checkLayer.y = _ref2[1];

  _ref3 = [0, 30], sendLayer.x = _ref3[0], sendLayer.y = _ref3[1];

  sendLayer.opacity = 0;

  subject = new Layer({
    x: 50,
    y: 50,
    width: 250,
    height: 100,
    backgroundColor: 'transparent',
    superLayer: screenLayer
  });

  subject.style = {
    fontSize: '2em',
    paddingTop: '.5em'
  };

  content = new Layer({
    x: 30,
    y: 200,
    width: 300,
    height: 100,
    backgroundColor: 'transparent',
    superLayer: screenLayer
  });

  content.style = {
    fontSize: '.8em',
    color: 'darkgrey',
    overflow: 'scroll'
  };

  subjectStr = 'Subject';

  contentStr = 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\ntempor incididunt ut labore et dolore magna aliqua.';

  subject.html = subjectStr;

  content.html = contentStr;

  Framer.Defaults.Animation = {
    curve: "spring(260, 30, 0, 0.1)"
  };

  checkLayer.states.add({
    change: {
      opacity: 0,
      rotationZ: -180,
      y: -40
    }
  });

  sendLayer.states.add({
    change: {
      opacity: 1,
      rotationZ: -180,
      x: -3,
      y: -6
    }
  });

  subject.states.animationOptions = content.states.animationOptions = {
    curve: 'bezier-curve',
    curveOptions: [.5, -1, 0, 1]
  };

  subject.states.add({
    disapear: {
      x: 300,
      opacity: 0
    }
  });

  content.states.add({
    disapear: {
      x: 300,
      opacity: 0
    }
  });

  checkLayer.states.next();

  sendLayer.states.next();

  screenLayer.on(Events.Click, function() {
    checkLayer.states.next();
    sendLayer.states.next();
    subject.states.next();
    return content.states.next();
  });

}).call(this);
